backend:
  name: github
  repo: karesztrk/WODster
media_folder: static/assets
public_folder: /assets
collections:
  - name: "blog"
    label: "Blog"
    folder: "content/posts"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    create: true
    publish_mode: "editorial_workflow"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "date" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list" }
